.\" This is a comment
.TH APPLICATION 1 "May 2020" "Description"
.SH NAME
my_application
\- Short Description
.SH SYNOPSIS
my_application [options] files
.SH DESCRIPTION
Short Description
.SH OPTIONS
.SS
.SS Arguments:
.TP
.B files
Files to open, may also be URLs
.SS Options:
.TP
.B \-v,  \-\-version
Show version information

This is some \fBbold\fR text.
